### ISSUE TITLE
add generic --set=foo=bar to ostreesetup

### ISSUE THREAD

**Issue by cgwalters** [pykickstart/pykickstart#133]
OSTree remotes are gaining options over time - we've supported e.g. `tls-ca-path` for a long time, but one can't configure this via the ks verb.  Similarly, I just added one: https://github.com/ostreedev/ostree/pull/627

It'd be a lot nicer if I could do today (just like the `ostree remote add` command has):

```
ostreesetup --osname="rhel-atomic-host" --remote="rhel-atomic-host" --ref="rhel-atomic-host/7/x86_64/standard" --url="http://download-node-02.eng.bos.redhat.com/devel/candidate-trees/Atomic-7.3-20161129.0/x86_64/ostree/repo/" --nogpg --set=unconfigured-state="This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register."
```

Rather than doing it in `%post` like:

```
ostree_remote=$(ls /etc/ostree/remotes.d/*.conf | head -1)
test -n "${ostree_remote:-}"
echo 'unconfigured-state=This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.' >> ${ostree_remote}
```

**Comment by clumens** [comment]
What we've done with other commands (authconfig being the most prominent example) is just make the command a pass through and send the whole arg string through to the underlying command.  Could something like that work here?

**Comment by cgwalters** [comment]
Not at the moment, there's no single ostree command for what's part of `ostreesetup`.  So we really may need to call it `--remote-set`, like `--remote-set=tls-ca-path=/etc/pki/tls/examplecom.crt --remote-set=unconfigured-state="Access to ExampleOS requires ONE BILLION DOLLARS"`.  That'd leave things a bit open in the future for options for other components (the repo/deployment model), which is distinct from the remote.
