### ISSUE TITLE
document package version pinning in kickstart config

### ISSUE THREAD

**Issue by davide125** [pykickstart/pykickstart#143]
It is possible to pin packages to specific versions in kickstart, using the same syntax that yum or dnf would use. Example: specifying
`rpm-4.11.3-21.el7.x86_64`
in the packages section will result in the installer picking that specific version, as show in the logs
`17:27:41,842 INFO packaging: selected package: 'rpm-4.11.3-21.el7.x86_64'`

This should be documented.

**Comment by dcantrell** [comment]
Send a pull request.
