### ISSUE TITLE
RHEL section of docs doesn't show version information

### ISSUE THREAD

**Issue by samveen** [pykickstart/pykickstart#181]
On readthedocs, the kickstart commands section for [RHEL](http://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-3-kickstart-commands-in-red-hat-enterprise-linux), all the sections mention details about which `Fedora` version that command was introduced in, not the expected `RHEL` version.

Can this be fixed so that I can see an appropriate `New in RHEL x.y` instead of `Fedora`?

**Comment by VladimirSlavik** [comment]
I concur that this limits the usefulness of the documentation significantly. However, given the way kickstart works, it is almost impossible to fix "properly".

One way to fix this could be retroactively adding to command parser docstrings (in master) information about past RHELs. I mean, not as code, just as docstrings. However, finding the right places to insert this could be pretty tricky, unless only docs generated for "latest" version (`DEVEL`) were considered. It would be a very significant effort, on the order of man-weeks.

(Estimated as the person who wrote majority of the official Red Hat RHEL 8 ks docs to date, and also as someone who has been spending past month or so on similar issues in kickstart code.)
