### ISSUE TITLE
Makefile needs to adjust for make release process

### ISSUE THREAD

**Issue by dcantrell** [pykickstart/pykickstart#221]
Since the spec file has been removed, I think some additional changes need to happen.  Here are my own notes on what I did for 3.13:

1) make release needs additional steps separated by &&.  bumpver, check, test, tag, po-pull, archive
2) make tag needs to commit the changes created for the tag.
3) make pypi fails, needs to use the new url process.  Will look at that later.

Assign this to me, I'm just opening this ticket for my own notes.

**Comment by bcl** [comment]
Looks like all of this is done except for pypi
