### ISSUE TITLE
RHEL7 support

### ISSUE THREAD

**Issue by pwnslinger** [pykickstart/pykickstart#279]
Hi, I just have noticed the latest version (`pykickstart-3.21`) at the time of opening this issue doesn't have any support for tags introduced in RHEL7. but I see there's a comment in latest release regarding this matter. 

```Add rhel7-branch to .travis.yml (dcantrel)```

I was wondering what's the progress on that?

```ksvalidator -l
DEVEL
F10
F11
F12
F13
F14
F15
F16
F7
F8
F9
FC3
FC4
FC5
FC6
RHEL3
RHEL4
RHEL5
RHEL6```

The output:

```The following problem occurred on line 15 of the kickstart file:

no such option: --vckeymap

The following problem occurred on line 29 of the kickstart file:

no such option: --boot-drive

The following problem occurred on line 30 of the kickstart file:

no such option: --type

There was a problem reading from line 45 of the kickstart file
```

**Comment by bcl** [comment]
Are you sure your system is setup correctly? When running from Fedora 30 (v3.20) it works fine, listing all the RHEL versions, and also when running from the git repo:

    PYTHONPATH=. ./tools/ksvalidator.py -l
