### ISSUE TITLE
Read the docs site missing new builds

### ISSUE THREAD

**Issue by jkonecny12** [pykickstart/pykickstart#289]
Last pykickstart documentation build was more than 2 months ago. Not sure what is happening there but new builds seems not to be triggered.

https://readthedocs.org/projects/pykickstart/

**Comment by bcl** [comment]
Manually rebuilt them. Not sure why it wasn't triggered automatically.

**Comment by poncovka** [comment]
Hi, we had a similar problem in Anaconda and we had to set up a new webhook instead of the GitHub service. See: https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by bcl** [comment]
> Hi, we had a similar problem in Anaconda and we had to set up a new webhook instead of the GitHub service.

Ah, ha! Thanks, it should be all setup now.
