### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [pykickstart/pykickstart#300]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by bcl** [comment]
I'm trying to figure out exactly what needs to be done for this and am having some problems:
 * I cannot log into weblate, I get a 500 server error
 * I do not want to give weblate commit or PR access to the main repo, we update translations at build time only.
 * I cannot find a guide for Fedora developers, are we supposed to setup weblate ourselves? Or is this a manual process that only you can do?

I think what I want to do is make a separate translation repo for weblate to access, like the way that cockpit-composer created cockpit-composer-weblate.

Like anaconda we have separate branches for Fedora and RHEL translations (see https://fedora.zanata.org/project/view/pykickstart?dswid=-7354) and I'd like to continue doing that.

**Comment by Jibec** [comment]
It's fine if you follow the same recommendations I did to other teams if that's the workflow you want to apply.

You just have to provide me the repo link with po and pot. And answer my questions.

I'll do first configuration and provide you admin rights so you can tune it if required.

Most of the work for you may be to change your automation.

About error 500, try again and send an email to translator mailing list if the issue still occurs.

**Comment by bcl** [comment]
weblate translations for pykickstart are here:

https://github.com/pykickstart/weblate

>     * [mandatory] which branch is your development branch?

master

>     * [mandatory] have you merged latest translation from Zanata and locked the project?

I have imported the latest translations, but the project is not locked -- we still need it for RHEL translations for now.

>     * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

License is GPL-2.0-or-later

>     * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
> 
>     * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

Not sure. Probably the python related ones, but I can always turn these on later, right?

> 
>     * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

I don't know what that means. My plan is to automate generation of new .pot file and push it to the weblate repo.

**Comment by Jibec** [comment]
thank you,

I started the configuration 
https://translate.stg.fedoraproject.org/projects/pykickstart/master/#information

could you please delete languages with 0 translated strings?



Please also move RHEL translation in related branches, you'll be able to 
add them too.

Either you create one folder per source' repo branch, or you create real 
branches. I'll adapt.

Zanata is retiring globally, not only Fedora related stuff.

**Comment by bcl** [comment]
> could you please delete languages with 0 translated strings?

Done. I think. I removed the .po files with no translations from the master branch and pushed it to github.

> Please also move RHEL translation in related branches, you'll be able to add them too.

I have created a rhel8-branch and a rhel7-branch with the current translations from Zanata, but moving to them needs approval from the RHEL translation team so I don't want to lock the project in Zanata until they are ready.

I'm not sure how to add the branches in weblate, and the UI is currently saying 'this translation is currently locked for updates." with no explanation.

**Comment by Jibec** [comment]
configuration is done: https://translate.stg.fedoraproject.org/projects/pykickstart/master/

bcl is Administrator of the project
about rhel branches, this is up to you, they will be able to import their work in Weblate without requiring any authorization from anyone

please don't merge translations back to master, weblate will do it when you'll configure the new components. To add new components, just copy the setting of the first component and everything should works fine.

weblate will:

- open PR when you new translations are done
- squash commits per author to limit the number of commits
- update all po files when you update pot (please don't update po files yourself)

from now on, please use the fedora translation mailing list of any question
