### ISSUE TITLE
Add ability to disable some checks

### ISSUE THREAD

**Issue by ephracis** [pykickstart/pykickstart#311]
When I am setting up multiple VLANs in my kickstart the ksvalidator gives the following:

> A network device with the name enp0s31f6 has already been defined.

Unfortunately I am running an automated build of the kickstart data disk using Ansible so my task that runs ksvalidator fails, since ksvalidator return non-zero. Even though my setup makes complete sense, as I need to specify the network device multiple times to set up multiple VLANs on that device.

I nice way to get pass this would be if it was possible to configure ksvalidator, either using a configuration file or command line args, to disable some of the checks.

**Comment by bcl** [comment]
It would be nice, yes, but would complicate things quite a bit. It might be better to examine the output (after stripping out the known false positives) and fail on that instead of the return code.
