### ISSUE TITLE
Absolute path information is not passed to _load_file

### ISSUE THREAD

**Issue by sreyan32** [pykickstart/pykickstart#313]
When a Kickstart file is supposed to be loaded via the function call:

[_load_file(filename)](https://github.com/pykickstart/pykickstart/blob/92b21402aecdb8dd8bc7039118a727baebeb717f/pykickstart/load.py#L88)

in `load.py`

Only the filename is passed, the absolute path is not passed with it. 

So Kickstarts files residing in directories like /usr/share directory are not loaded and fails with error message no such file or directory.

To rectify this problem I had to make an ugly hack by adding the following line in the beginning of `_load_file
`
`filename = '/usr/share/spin-kickstarts' + filename`.

This whole error manifests when a command like the following is run :

```
livecd-creator --verbose \
--config=/usr/share/spin-kickstarts/fedora-livecd-desktop.ks \
--fslabel=Fedora-LiveCD \
```

**Comment by bcl** [comment]
I don't see how that can be happening. What does the error look like when it fails?

If you look at parser.readKickstart it is using the full filename passed to it, passing that to load_to_str which calls _load_file.

**Comment by sreyan32** [comment]
This error happens when I do something like:

```
livecd-creator --verbose \
--config=/usr/share/spin-kickstarts/fedora-livecd-desktop.ks \
--fslabel=Fedora-LiveCD \
```

Try running that and see if you get the error. 

Please note the Kickstart file must be kept in a long directory path like the one shown above.

**Comment by bcl** [comment]
Sorry, cannot reproduce this and I don't see anything with the code that would cause a problem.
