### ISSUE TITLE
RHEL-8 commands are not backported

### ISSUE THREAD

**Issue by jkonecny12** [pykickstart/pykickstart#320]
I know that at least `RHEL8_Repo` is missing there could be more.

**Comment by bcl** [comment]
Please be more specific about what you are seeing. Also, if this is RHEL related it needs to be in bugzilla, not just a github issue.

**Comment by jkonecny12** [comment]
Sorry, I wasn't clear enough. I'll try to explain it better.

Right now we are doing rebase of Anaconda. Thanks to that we are running RHEL-8 and Rawhide tests together on the new rhel8 branch. That way we found that RHEL-8 commands are not backported to Rawhide.

So there are not missing RHEL-8 commands on the RHEL-8. However, existing RHEL-8 commands (at least `RHEL8_Repo`) are not backported to master branch.

See here https://installer-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/anaconda-rawhide-PR/2486/artifact/result/tests/test-suite.log. These are Rawhide tests running on RHEL-8 branch. Pykickstart should known the RHEL-8 commands classes.

**Comment by bcl** [comment]
Ah, I see what happened. They're actually there, but not as RHEL8_Repo and RHEL8_Url. We should be able to just add those as alises for F30_Repo and F30_Url

**Comment by jkonecny12** [comment]
Ohh, ok. Thanks for that!

**Comment by bcl** [comment]
Closed by #321 (not sure why it didn't do this automatically)
