### ISSUE TITLE
Version missing in the main module

### ISSUE THREAD

**Issue by VladimirSlavik** [pykickstart/pykickstart#323]
There is no `pykickstart.__version__` or similar place to access pykickstart version.

See eg.: https://github.com/storaged-project/blivet/blob/3.2-devel/blivet/__init__.py#L23

**Comment by bcl** [comment]
What do you plan on using it for? pykickstart is somewhat unusual in that there is support for all previous versions of kickstarts.
You can figure out what the latest supported version is by looking at `pykickstart.version.versionToLongString(pykickstart.version.DEVEL)`

**Comment by VladimirSlavik** [comment]
Hi Brian, here's the reason:
- https://bugzilla.redhat.com/show_bug.cgi?id=1410595
- https://github.com/rhinstaller/anaconda/pull/2724
Ideally the output kickstart would also contain versions of pykickstart and blivet.

I'm not sure if you'd want this as a static line that must be edited every time, though...
