### ISSUE TITLE
Weblate as a git submodule

### ISSUE THREAD

**Issue by CMeza99** [pykickstart/pykickstart#327]
Suggesting making `https://github.com/pykickstart/weblate.git` a git submodule in `./po`.
This way it is easier to track and push changes to weblate. Also files are no longer need to be downloaded and copied (as it is currently in the `Makefile`), rather the submodule gets updated.

i.e.:
```sh
git submodule add -- https://github.com/pykickstart/weblate.git po
git submodule update --init -- po
```

**Comment by bcl** [comment]
Sorry, no. I can't stand submodules. The current setup is working well enough. Thanks.
