### ISSUE TITLE
Remove old EOL OS support

### ISSUE THREAD

**Issue by CMeza99** [pykickstart/pykickstart#328]
Removing old versions of Fedora, Redhat, etc will:
* reduce the number of tests required; speed up test execution time
* de-clutter documentation so what is currently relevant is more clear

For users on EOL OSes and for reference, the last 2 EOL versions of each OS should remain.

**Comment by bcl** [comment]
pykickstart is written to be able to be used across all the various releses. I don't see enough benefit in trying to curate the list. Thanks.
