### ISSUE TITLE
--mkfsoptions has no effect for `btrfs` and `part` commands

### ISSUE THREAD

**Issue by daetoCh0** [pykickstart/pykickstart#332]
The system will install, but it appears to ignore (or does not parse) the `--mkfsoptions`. I have tested the following partitioning config:
```
part /boot --fstype="xfs" --ondisk=sda --size=1024
part /boot/efi --fstype="efi" --ondisk=sda --size=1024 --fsoptions="umask=0077,shortname=winnt"
part swap --fstype="swap" --ondisk=sda --size=16384
part btrfs.0 --fstype="btrfs" --fsoptions="compress=zstd" --ondisk=sda --grow --mkfsoptions "--checksum xxhash"
btrfs none --label=BVOL_ROOT btrfs.0 --mkfsoptions "--checksum xxhash"
btrfs / --subvol --name=@root LABEL=BVOL_ROOT --mkfsoptions "--checksum xxhash"
btrfs /home --subvol --name=@home LABEL=BVOL_ROOT --mkfsoptions "--checksum xxhash"
```

Note that I have also tested the placement of this parameter in both of (1) only the main `part btrfs.0 [...]` and (2) only the `btrfs none [...]` lines.

The resulting BTRFS file system shows a checksum type of `crc32c`, which is the `mkfs.btrfs` default, and not the expected value of `xxhash64`.
```
$ sudo btrfs inspect-internal dump-super /dev/sda4 | grep csum_type
csum_type		0 (crc32c)
```

**Comment by bcl** [comment]
This is an Anaconda bug, pykickstart just passes through the data. Please file a bug with the anaconda component at https://bugzilla.redhat.com/ with logs (especially the program.log which will show what mkfs options were passed, and storage.log).

**Comment by dev-uhuru** [comment]
That is still happening, has a bug be filled for anaconda? Thanks for this bug report I've been trying all combinations I could think of in the past hours. Guess I'll manually call mkfs.btrfs in %pre-install to reformat.
