### ISSUE TITLE
Report that wireless options have no effect

### ISSUE THREAD

**Issue by missic** [pykickstart/pykickstart#338]
https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/advanced/Boot_Options/#sect-boot-options-removed lists 'essid=, wepkey=, wpakey=' options as removed due to network configuration being handled differently than in the past.
ksvalidator should point this out.
In fact, I have tried to install f32 with those options and the process failed with an error message about "devicewifi" and "get_carrier" (unfortunately I don't have the full error message handy, but removing those options and installing via ethernet cable worked).

**Comment by bcl** [comment]
Those are not kickstart options, those are kernel cmdline options.

**Comment by missic** [comment]
Those are also listed as arguments to the 'network' kickstart command: https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#network

**Comment by jkonecny12** [comment]
@rvykydal could you please tell us state of this in Anaconda?

**Comment by bcl** [comment]
> Those are also listed as arguments to the 'network' kickstart command: https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#network

If there is a problem with them in that context please file a bug against Anaconda at https://bugzilla.redhat.com

**Comment by Woi** [comment]
There is already a bug report/feature request: https://bugzilla.redhat.com/show_bug.cgi?id=1927325

Would be nice to have this documented. It took me several hours to find out why it's not working
