### ISSUE TITLE
Clean up Questions Surrounding Deprecation

### ISSUE THREAD

**Issue by bcl** [pykickstart/pykickstart#350]
There's some question about the correct behavior of pykickstart's deprecated commands.
It appears that in some cases deprecation has removed/disabled parsing of the command immediately.
It should instead continue to be parsed, but include a deprecation warning.

Need to clean this up and clearly document how to deprecate commands and arguments.

**Comment by VladimirSlavik** [comment]
Thank you!

**Comment by bcl** [comment]
Fixed by #356
