### ISSUE TITLE
Change default for "updates"

### ISSUE THREAD

**Issue by VladimirSlavik** [pykickstart/pykickstart#359]
Currently, `updates` defaults to `floppy` if called with no options. That's a poor default for 2020, but what would be a good one? I think just having no default would work best. Other opinions welcome.

I'm ready to do the work once it's clear what is wanted.

**Comment by poncovka** [comment]
No default sounds good to me.

**Comment by bcl** [comment]
I think it should require an argument, either 'floppy' or a URL-like thing (it looks like URLs or devices are valid) and default to none so that ksvalidate and anaconda return an error when they hit a bare 'updates'.

**Comment by VladimirSlavik** [comment]
Turns out I'm not ready. The option seems to resist pretty well any changes. Even just subclassing the command and a noop `add_argument` to bump the version in docs leads to test failures.

**Comment by bcl** [comment]
Fixed by #361
