### ISSUE TITLE
Removed commands are not marked in documentation.

### ISSUE THREAD

**Issue by VladimirSlavik** [pykickstart/pykickstart#360]
For options, documentation mentions when they were added, changed, deprecated, removed. For commands, the last state is never mentioned.

To rephrase in terms of code: There is actually a great number of commands that have been deprecated a long time ago, and they are not present in new handlers, so these are effectively "removed". However, the (generated) documentation does not reflect this in any way.

Here's a list:

* interactive
* key
* langsupport
* lilo
* lilocheck
* monitor
* mouse
* upgrade

(And probably other recently removed ones.)

**Comment by bcl** [comment]
This could probably be handled by changing them to a `ComandRemoved` class that raises an error and sets some info about which version it was removed in instead of dropping it from the list.

**Comment by bcl** [comment]
See PR #365

**Comment by bcl** [comment]
Fixed by #365
