### ISSUE TITLE
autopart needs option to disable it or for it not to be the default

### ISSUE THREAD

**Issue by paulraines68** [pykickstart/pykickstart#377]
My kickstart file has no partition directions.  The only lines related to storage  in the whole ks.cfg file are zerombr and bootloader . For kickstarts previous to CentOS Stream 8 when the kickstart had no partition info, it would present the GUI with the warning icon in the Installation Destination saying "Kickstart insufficient".  I could go in and setup the partitioning I wanted by hand and then proceed with the reset of the automated kickstart directions (mainly the package list).

Since CentOS Stream 8, this still works as long as there is not enough free unpartitioned space on the detected disks for anaconda to autopartition (though the error is different now saying insufficient space).  However, if there is enough free space it will proceed to install to that free space and never give me a chance to do the partitioning I want by hand.  I very much dislike this new behavior.  

It basically seems like 'autopart' is now assumed to be present by default if it is not in the kickstart file and there are no other partitioning directives.  These also seems very dangerous especially if a system has disks with no standard partition table because they are being used in a raw mode (I have had GFPS disks wiped out by anaconda in the past due to this)

If the new "default to autopart" behavior cannot be reversed we need at least a "autopart --disable" option to force interactive partitioning if no other partition directives exist.

I tried "ignoredisk --interactive" but just got a message it was deprecated and it was ignored and anaconda proceed to autopartition and install on the free space.  The latest docs at https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#id22 do not say this is deprecated.

**Comment by paulraines68** [comment]
After some experimenting, it seems I can essentially get the behavior I want by adding 'reqpart' to the kickstart with no other partitioning lines.

This is a bit hacky and ideally there was more direct support 

Maybe another idea is an option like "reqapproval" that would not proceed with any automated or requested partitioning (or even other things like source or package selection) till manual approval after review is given.

**Comment by poncovka** [comment]
Hi, I think that the best option is to fix the regression. I have opened a pull request for upstream: https://github.com/rhinstaller/anaconda/pull/3254

**Comment by bcl** [comment]
@poncovka is correct, this is an issue with Anaconda not kickstart itself. Thanks!
