### ISSUE TITLE
Add --repo-option option to url and repo commands

### ISSUE THREAD

**Issue by bcl** [pykickstart/pykickstart#392]
This will enable passing depsolver specific options without tightly coupling kickstart to the exact options or depsolver.

This will also need Anaconda support.

Related to issue #378

**Comment by bcl** [comment]
Do we still want to do this? Looks like the dnf changes made it in, but I'm not sure of the state of dnf5 or if we still want to add this.

**Comment by jkonecny12** [comment]
I'm for closing this. I don't heard about this requirement for a long time. If someone still want to have this, feel free to write.
