### ISSUE TITLE
Don't set the global gettext domain

### ISSUE THREAD

**Issue by poncovka** [pykickstart/pykickstart#405]
Pykickstart shoudn't call `gettext.textdomain("pykickstart")` and rely on using the global domain. If the global domain is changed, the pykickstart translations will no longer work. The domain should be specified for every gettext call.

For example:
https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/core/i18n.py#L25
https://github.com/storaged-project/blivet/blob/3.5-devel/blivet/i18n.py#L40

**Comment by bcl** [comment]
@poncovka Did something change recently to reveal this problem? I'm pretty sure translations were working in the past.

**Comment by bcl** [comment]
Thanks for spotting it! I'm mildly surprised it hasn't broken anything :)
