### ISSUE TITLE
Installing multiple keys to authorized_hosts with sshkey

### ISSUE THREAD

**Issue by jasontibbitts** [pykickstart/pykickstart#413]
I need to install more than one key to root's authorized_keys file and wanted to do it the "right way" instead of just using %post.

Using two sshkey lines appears to work, but I get a warning:

> An ssh user with the name root has already been defined.

Everything appears to be set up correctly but I just wanted to see whether using sshkey in this manner is supported since I don't want it to break in the future.  If there is a better way I will happily use it.

**Comment by bcl** [comment]
This is a valid use -- I double checked pykickstart and anaconda and both treat each entry as a separate operation with anaconda appending any subsequent entries to authorized_keys, and internally it is stored as a list so it doesn't matter if there are duplicates. The warning may be useful in cases where you didn't mean to set the key on the same user so I think it's ok to leave it.

**Comment by markfaine** [comment]
This fails for me as well but breaks the build:

![image](https://github.com/pykickstart/pykickstart/assets/949949/d38cd1fa-afc8-41ab-a8f3-740c43352326)

**Comment by VladimirSlavik** [comment]
I'll just leave this here?
- https://www.redhat.com/en/blog/end-maintenance-red-hat-enterprise-linux-7-almost-here
- https://access.redhat.com/support/policy/updates/errata#Maintenance_Support_2_Phase
