### ISSUE TITLE
Copying /etc/resolv.conf no longer works in %post

### ISSUE THREAD

**Issue by bcl** [pykickstart/pykickstart#429]
Thanks to systemd's takeover of /etc/resolv.conf you can no longer just copy the host/mock file into the chroot and have it work. Need to figure out what does work in order to enable DNS for those cases where it is needed in `%post` and update the documentation.

**Comment by poncovka** [comment]
We have the workaround documented here: https://anaconda-installer.readthedocs.io/en/latest/common-bugs.html#missing-etc-resolv-conf-for-post-scripts

**Comment by bcl** [comment]
Thanks! I'll update the pykickstart docs as well.
