### ISSUE TITLE
Add --removable command to bootloader

### ISSUE THREAD

**Issue by LukeShortCloud** [pykickstart/pykickstart#439]
When using GRUB 2 (I am unsure about LILO), it is possible to install the bootloader in a portable way using this command:

```
$ sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=fedora --removable
```

This allows Linux to be bootable on any computer which is useful for portable flash drives and external drives.

Kickstart could add a `bootloader --removeable` argument to add this functionality. If this is something I can help develop and contribute upstream, I would be happy to take any hints you can provide!

**Comment by bcl** [comment]
This would have to be something done by Anaconda. Please discuss with them first. https://github.com/rhinstaller/anaconda/

**Comment by LukeShortCloud** [comment]
Thanks for the direction and insight!

**Comment by LukeShortCloud** [comment]
I opened a request for enhancement for the Anaconda project here: https://bugzilla.redhat.com/show_bug.cgi?id=2173263
