### ISSUE TITLE
partition: filesystem label not set when used with --noformat

### ISSUE THREAD

**Issue by Woi** [pykickstart/pykickstart#453]
`part /home --noformat --onpart="sda5" --label="home"` does not set label for existing filesystems.

Use case: 
Data on existing but unlabelled home partitions should survive system installation. Afterwards they should be labelled `home`  for future usage, because _it is safer to use labels than absolute partition names_ [1].

Code snipped for reproduction:
Prepare a test installation:
```
ignoredisk --only-use=sda
zerombr
clearpart --all --initlabel --drives=sda 

reqpart --add-boot
bootloader --location=mbr --boot-drive=sda
part / --fstype="ext4" --size=20480 --ondisk="sda"
part swap --fstype="swap" --size=4096 --ondisk="sda"
part /home --fstype="ext4" --grow --label="test"
```
Reboot to test installation and check filesystem label:
`lsblk -o name,label,mountpoint /dev/sda5`

Use the test installation to reproduce the described behaviour. Note the changed line starting with `part /home`:
```
ignoredisk --only-use=sda
zerombr
#Clear all but sda5, which should be /home
clearpart --drives=sda --list=sda1|sda2|sda3|sda4|sda6|sda7|sda8

reqpart --add-boot
bootloader --location=mbr --boot-drive=sda
part / --fstype="ext4" --size=20480 --ondisk="sda"
part swap --fstype="swap" --size=4096 --ondisk="sda"
part /home --noformat --onpart="sda5" --label="home"
```

Reboot to second test installation and check filesystem label again:
`lsblk -o name,label,mountpoint /dev/sda5`

Observed behaviour:
```
NAME LABEL  MOUNTPOINT
sda5 test   /home
```
Expected behaviour:
```
NAME LABEL  MOUNTPOINT
sda5 home   /home
```

[1] Quoted from `partition --onpart ` documentation
https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#part-or-partition

**Comment by bcl** [comment]
Thanks for the report, but this is not a bug in pykickstart, it is a bug in how Anaconda uses it. Implementation bugs should be filed with Anaconda. My guess, without looking, is that the `--noformat` prevents Anaconda from re-labeling the filesystem.
