### ISSUE TITLE
pip install of pykickstart doesn't install requests dependency

### ISSUE THREAD

**Issue by bcl** [pykickstart/pykickstart#465]
The current `pyproject.toml` is incorrect, the dynamic entries have to point to files, as described in the documentation here - https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata so that may be why `requests` isn't installed. But I have been unable to fix it.

I have tried:
* Adding a simple `dependencies` section with `requests` in it.
* Adding a new requirements.pip.txt file with `requests` in it.
* Removing the `install_requires` in setup.py as a diagnostic (tox needs it)

I am testing it by running (from within a py3.11 venv): `python3 -I -m pip install -vvv --check-build-dependencies -I .` and it installs pykickstart into the venv, but totally ignores any kind of dependency I add -- including totally bogus ones.

**Comment by supakeen** [comment]
I'll assign this to me and take a look for you.
