### ISSUE TITLE
ostreecontainer option installs custom OCI image as ostree-unverified-registry instead of ostree-image-signed

### ISSUE THREAD

**Issue by joshua-stone** [pykickstart/pykickstart#505]
I have a kickstart file that installs a [custom OCI image](https://github.com/joshua-stone/rose-os/pkgs/container/rose-os-silverblue), using [Fedora Rawhide](https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/iso/):

https://github.com/joshua-stone/rose-os/blob/58b5c540a6002d9c8ecad01a9067913afdf32b68/anaconda-ks.cfg

As I understand it, container configuration files and public keys have to be included at the time of pulling to ensure that [`--no-signature-verification`](https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#ostreecontainer) isn't required at install time. Those files appear to be put in the right place:

```
$ cat /root/ks-pre.log
'/run/install/repo/cosign.pub' -> '/usr/etc/pki/containers/rose-os.pub'
'/run/install/repo/files/usr/etc/containers/policy.json' -> '/etc/containers/policy.json'
'/run/install/repo/files/usr/etc/containers/registries.d/rose-os.yaml' -> '/etc/containers/registries.d/rose-os.yaml'
'/run/install/repo/files/usr/etc/profile.d/rose-os-just.sh' -> '/etc/profile.d/rose-os-just.sh'
```

https://github.com/joshua-stone/rose-os/blob/main/files/usr/etc/containers/registries.d/rose-os.yaml
https://github.com/joshua-stone/rose-os/blob/main/files/usr/etc/containers/policy.json

It doesn't appear that the image is being installed as `ostree-image-signed` during the Kickstart installs, rather as `ostree-unverified-registry`:

```
$ grep unverified -r /var/log/anaconda
/var/log/anaconda/syslog:20:39:37,304 INFO ostree-containe:Fetching ostree-unverified-registry:ghcr.io/joshua-stone/rose-os-silverblue:41
/var/log/anaconda/journal.log:Sep 02 20:39:37 fedora ostree-containe[3086]: Fetching ostree-unverified-registry:ghcr.io/joshua-stone/rose-os-silverblue:41
$ rpm-ostree status --booted 
State: idle
BootedDeployment:
● ostree-unverified-registry:ghcr.io/joshua-stone/rose-os-silverblue:41
                   Digest: sha256:c91aa7f6967ba99b41b3a14229b16ee77956a6b5cdddb0bcb2cb66a209d4d0a8
                  Version: 41.20240902.n.0 (2024-09-02T15:20:52Z)
```

Is there another configuration option I need to set?

**Comment by bcl** [comment]
Sorry, pykickstart isn't the right place to ask, it is just the parser for the kickstart file. Implementation is handled by Anaconda, so it would be better to ask them. Their github repo is here - https://github.com/rhinstaller/anaconda/
