### ISSUE TITLE
xconfig  --startxonboot causing 'tuple' object has no attribute 'option_strings'

### ISSUE THREAD

**Issue by Athwale** [pykickstart/pykickstart#516]
The ksvalidator returns errors when `xconfig  --startxonboot` and similar commands are in the ks file.
The exception originates on line 185 in options.py `option = action.option_strings[0]`

```
$ ksvalidator ks.ks 

Checking kickstart file ks.ks

'tuple' object has no attribute 'option_strings'
```

It seems the code around line 185 must be:
```
action = option_tuple[0]
option = action[0].option_strings[0]

if action[0].deprecated:
```
Although this used to work before with the same file, so I am not sure what changed where and if this is the correct fix.

**Comment by bcl** [comment]
What version of pykickstart are you using? And what version of python? There was a recent fix made in pykickstart v3.60 to handle new behavior from python 3.12.7 and later.

**Comment by Athwale** [comment]
pykickstart-3.52-3.fc40.noarch
Python 3.12.7
yum upgrade pykickstart says this is the latest version on F40.

**Comment by bcl** [comment]
@Athwale  Do you have an example kickstart? I can't get it to fail for me, even though I know it should :/

**Comment by Athwale** [comment]
```
### File: base.ks
# Kickstart base with basic configuration

# Condition evaluation ok.

# X Window System configuration information
xconfig  --startxonboot

# Keyboard layouts
keyboard --xlayouts='us','cz (qwerty)' --switch='grp:alt_shift_toggle'

# Root password
rootpw --iscrypted --lock locked
```

**Comment by bcl** [comment]
It actually should not fail with `pykickstart-3.52-3.fc40.noarch` -- adam patched it and it works fine for me here.
What version of python3-kickstart do you have? It should always match pykickstart but may as well check since this isn't making sense.

**Comment by bcl** [comment]
Whew! Glad you figured it out :)
