### ISSUE TITLE
RFE: Allow setting firewall zone for network interface

### ISSUE THREAD

**Issue by opoplawski** [pykickstart/pykickstart#69]
It would be helpful to be able to specify the firewall zone for a network interface.

**Comment by clumens** [comment]
It'd be very easy to do this on the pykickstart side.  It's just another option.  Is there an open issue for anaconda, where the bulk of the real work would take place?

**Comment by dcantrell** [comment]
Any update here?  A corresponding anaconda bug?

**Comment by opoplawski** [comment]
Filed anaconda RFE.

**Comment by opoplawski** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1716008
